### ISSUE TITLE
Error Handling Example

### ISSUE THREAD

**Issue by adamklaff** [jondot/sneakers#129]
Apologies if this is overly basic, but I get timeout errors when retrieving from an external API sometimes and I want to requeue the jobs. I've looked over the docs but I just wanted to make sure I'm understanding how to structure my code correctly:
```
def work(msg)
		data = JSON.parse(msg)
		data = API.retrieve(data['token'],data.fetch("list")
		data.each do |k,v|
 			do some stuff
		ack!
		end
	end
```

I sometimes get the specific Faraday:ConnectionTimeout error. Would I need to rescue from that inside of the work method? Where would handle the requeuing inside my worker class?

**Comment by sharshenov** [comment]
```ruby
def work(msg)
  data = JSON.parse(msg)
  retries = 0

  begin
    data = API.retrieve(data['token'],data.fetch("list")
  rescue Faraday:ConnectionTimeout => ex
    if retries < 5
      retries += 1
      sleep 1
      retry
    else
      reject!
    end

  else
    data.each do |k,v|
        do some stuff
    end
  end

  ack!
end
```
Task will be retried for 5 times before being rejected.

**Comment by jondot** [comment]
@adamklaff when doing API calls like this, since the network sometimes may be glitchy I would use @sharshenov advice and retry before failing the job. I would even suggest to find a Faraday middleware that does _exponential backoff_ or any kind of other retry policy. See here:
https://github.com/lostisland/faraday/blob/master/lib/faraday/request/retry.rb

For "heavier" scenarios you can take a look at Sneakers' [retry handler](https://github.com/jondot/sneakers/blob/87b888f108b333a0ebb25bfd1a8c3e70487a7c26/lib/sneakers/handlers/maxretry.rb) which somehow takes this concept and uses a queue to manage it.

**Comment by jondot** [comment]
PS - this issue is now materialized to a Wiki entry https://github.com/jondot/sneakers/wiki/Retry :)

**Comment by adamklaff** [comment]
This is really helpful. Thanks!
