### ISSUE TITLE
Automatically recover consumer

### ISSUE THREAD

**Issue by sevos** [jondot/sneakers#145]
Hi,

I was reviewing this gem and it seems to me that it happened to not enable recover_cancelled_consumers flag on the worker queue channel.

The flag causes the consumers to resubscribe to queues after network failure recovery. You can see that in the bunny gem code here: https://github.com/ruby-amqp/bunny/blob/master/lib/bunny/channel.rb#L1651

IMHO, since this gem focuses on simplicity, it should enable this option by default.

**Comment by michaelklishin** [comment]
This is *not* a flag for consumer recovery after a network failure. Consumers are recovered right after queues and bindings without any flags. This flag means that Bunny will attempt to recover a consumer that was cancelled by the server (e.g. because the queue was deleted). There's a similar flag for recovering connections closed via management UI. Both are opinionated decisions and disabled by default. They can easily lead to zombie apps/consumers that cannot be disconnected/cancelled via management UI because they will immediately recover.

**Comment by sevos** [comment]
Good point! My mistake with the interpretation of the meaning of this flag. However, as you may know, there is another use case, HA failover, when the queue was existing on the node, which failed. In that case consumers connected to other nodes would also receive the cancel notification. How would you approach this when using sneakers?

**Comment by michaelklishin** [comment]
RabbitMQ 3.4.0+ should re-add your consumer automatically. I'm not against Sneakers having a way to configure this option but the way you described it was incorrect.

**Comment by anpr** [comment]
If I understand correctly, sevos was discussing the following case:
in a clustered setup, the node on which the queue is located fails, but the client listens on a different node. 

According to [the docs](https://www.rabbitmq.com/consumer-cancel.html), a cancel notification is sent to the client in this case. It would be convenient if there would be a way to configure sneakers such that it handles this message and automatically reconnects.

Does that make sense? We're planning to run on a clustered setup and that would be useful to have.

**Comment by michaelklishin** [comment]
@anpr: I was referring to the same scenario. But starting with 3.4.0 (IIRC), the consumer will be re-added for you automatically (as long as your client is connected to a mirror that didn't fail). There is no need for it to reconnect.

Having a way to register consumer cancellation callbacks is OK, it's just not as crucial as it may sound with recent server versions.

**Comment by mltsy** [comment]
Oh dang!  I think this is what I've been struggling with for weeks!  It sounds like it the consume re-connects to a mirror node, it's fine, but if it connects to a non-mirror node, it might be cancelled?  I would like for the consumer in my case to keep trying to re-connect until it reaches a node that doesn't cancel it.  Sounds like maybe I do need to use the recover_cancelled_consumers flag for this case?  I'l look into it, but since it's been 4+ years, if anybody has any more up-to-date pointers on this, I'd be grateful for them!
