### ISSUE TITLE
always sending ack

### ISSUE THREAD

**Issue by ninjonxb** [jondot/sneakers#173]
Hi, I am curently getting started with sneaker and I am trying to figure out why ack is always sent automatically instead of when I do 'ack!' (I just started with rabbitmq yesterday so I am learning that also).  
My basic problem right now. The worker is failing (which is a different issue, it is just a single line trying to turn a string into json). The message is not being returned to rabbitmq though. 
In the Sneakers.configure I have:
```
ack: true
```
I got around the issue by surrounding everything in an exception but that would require me to accept all errors and that is not really great (plus makes it harder to get the stack trace), 
Is there a way to configure it to send the manual_ack (from bunny gem) and require me to manually send !ack and not do it for me?
Here is the little bit of code:
initializer
```
require 'sneakers'
Sneakers.configure(
  daemonize: true,
  amqp: 'hide',
  log: 'log/sneakers.log',
  pid_path: "tmp/pids/sneakers.pid",
  threads: 1,
  workers: 1,
  ack: true,
  heartbeat: 20
)
```
worker
```
class ConnectinputWorker
  include Sneakers::Worker
  from_queue "some_queue"

  def work(raw_event)
    begin
      sleep(10)
      event_params = JSON.parse(raw_event)
    rescue Exception => e
      puts "FAIL"
      puts e
      requeue!
    end
  end
end
```

**Comment by jondot** [comment]
Hi,
Sneakers will take the return value of your `#work` method, and if it is `true` will ack, otherwise it will nack. So make sure the last return value maps to that semantics.
You can explicitly force this value by saying "ack!" or "nack!" as the last statement of the work body.

**Comment by ninjonxb** [comment]
How should that work if #work errors out completely. It looks like it is still sending the ack. I can handle it with the exception like above, but I would prefer in the case of a strange edge case pops up that instead of loosing the message I could have it stay in the queue until I fix the edge case.  
Originally my code was this:
```
class ConnectinputWorker
  include Sneakers::Worker
  from_queue "some_queue"

  def work(raw_event)
      event_params = JSON.parse(raw_event)
  end
end
```
and when it errored out the ack was sent.

**Comment by jondot** [comment]
I understand now. You should take a look at a concept of handlers. In this case, a task is ack'd on RabbitMQ but is flagged as 'reject'. 
If a 'poison' task would return to the queue, all of your workers would be stuck in endless error tasks. (take bad task, get error, return to queue, take next task - which is the same one, get error, return to queue, forever).

This is why usually you would either:
1. catch-all, and explicitly push such a task to a queue of your choosing
2. use a dead-letter-exchange, configured at RabbitMQ side
3. use a different handler strategy from Sneakers (see https://github.com/jondot/sneakers/tree/master/lib/sneakers/handlers). Start with taking a look at the `oneshot` handler which is the handler that causes the behavior you're seeing.

**Comment by ninjonxb** [comment]
Thank you for the info, I think I got it working the way I want it to.
Couple quick questions:
-Is there a way using Sneakers do the following scenario:
--Pull a message that says "xyz". At that time also pull all messages from that queue with the same message and mark as acknowledged. One of the issues I am running into (which is technically outside of rabbitmq) is messages being queued from multiple sources that only need to run once (until it is no longer in the queue, than if it is queued again it needs to run again). It is not harmful it runs multiple times just a waste of resources. 

-I am also curious about the sneaker configuration.
Since posting this message I created another worker class using the same initializer (except I increased the worker count to 2).
If I have the worker count set to 2 and I am calling 2 different worker classes when I call the rake task.
Does this create 4 workers or are the 2 workers bounce back and forth between the 2 queues?
I tried looking at running processes and I am still not sure. 
If it is the case that it creates 4 workers, is there a way I can tell it how many workers for each worker class?
If it is creating 2 workers that bounce between the 2. How does it bounce back and forth? My concern is I have one queue that has about 134k records in it right now (it did a large push but is shrinking more than it is growing) and another queue that only gets a few messages a minute (or will soon). I want to ensure that my larger queue does not stop that other queue from being processed.

Thanks,
Jon

**Comment by rud** [comment]
I can chime in on you message deduplication scenario, your first question. RabbitMQ assumes message independence, and works well with it. Messages can arrive to consumers out of order due to retry, but in general you get FIFO behaviour. 

You cannot effectively go through a queue and find all messages similar to a message you have on hand. Instead, you are supposed to take them "one at a time" in the order you get them and completely handle them. If you want to perform deduplication with some recency, one design is to have a list of "recently handled" messages, and check your new message against that list. If you have a match, just send an `:ack` back and you're done with the duplicated message. Such a "recently handled" list could be in your database or a redis instance all workers refer to. Just remember to expire things on the "recently handled" list according to how long it is relevant.

Does that make sense?

**Comment by rud** [comment]
@ninjonxb for the other question about parallel work, I believe you get at least 1 thread per worker, and multiple if you ask for it. You can also configure to get multiple worker processes, each with multiple threads. Note this can consume quite a few database connections, so don't go too crazy. Work will happen for all consumers, as long as they have messages in their queues.

**Comment by ninjonxb** [comment]
It does. I am currently looking at implementing such a feature just a little complicated since I need to choose some random number as far as what is acceptable.
Nothing strictly says that 10 minutes after it is queued and processed it won't need to be processed again. All that matters is that if it is in the queue 10 times it only needs to be processed once, but as soon as all instances of it leave the queue it is assumed as needing to be processed again.
That will require some playing with to get right.

**Comment by rud** [comment]
@ninjonxb Well, if that's your rule, might I propose a small idea that might allow you to move forward: 
* let us assume a new distinct message `A` is received by a worker; add `A` to the "recently handled" list
* enqueue a message to the same queue you got `A` from. This message should mean: we're done with the `A`'s, all duplicate `A`s have now been handled. Once you see that message in a worker, remove `A` from the "recently handled" list
* while `A` is still on the "recently handled" list, ignore all other `A` messages received by the worker

Now, this is not 100% exact as consumers will be going through the queue in parallel, but I think it will probably behave better than an arbitrary "5 minutes" limit. You might want to have a some time to live (TTL) on the "recently handled" values, so that you don't ignore messages forever if you lose a few messages for any reason.

Thoughts?

**Comment by ninjonxb** [comment]
I like that idea. Made easier since each message in the queue corresponds to a specific object I should be able to just add a flag to it for that.  
I am less worried about the occasional lost message (at the moment) than I am about the significant waste of resources and horrible backlog. Looking at my queue currently at 125,863 messages, I would not be surprised at all to find out that 15-20k of those were duplicates. Made worse when these messages take about 30 seconds to process each.

Thanks!

**Comment by rud** [comment]
There is a bit of an adjustment period when switching to designing solutions based on queues and asynchronous processing. Happy hacking.

**Comment by jondot** [comment]
Thanks guys, closing and noting this under 'to document' per roadmap discussions.

**Comment by gazeldx** [comment]
Cool explain! Thanks guys. This is a good design. This really broadens my horizon.
