### ISSUE TITLE
Comma-separated backtrace is hard to read

### ISSUE THREAD

**Issue by NIHERASE** [jondot/sneakers#199]
If a worker fails then exception's backtrace gets joined in a single comma separated string and that is a real pain to read.

What was the thinking behind this? Why does it show only 50 first entries?
https://github.com/jondot/sneakers/blob/master/lib/sneakers/worker.rb#L116

**Comment by justin-yesware** [comment]
The reason for using comma separated instead of newlines is to keep the log statement to a single line. When run in a multi-threaded environment it's possible to get multiple of these at the same time, which can result in multiple backtraces being interleaved in the log depending on the logger. This single-line log statement also works well with log tools that search for lines that match a search pattern and don't always do a good job of getting the full backtrace as part of it when it spans multiple lines.

The 50 limit is somewhat arbitrary, but meant to prevent the backtrace from being excessively large. 50 seemed like a reasonable enough number to give you some hint of where the problem is at. You could always submit a pull to make it configurable.

**Comment by NIHERASE** [comment]
Could `"#{e.message} #{e.backtrace.join("\n")}"` be used instead?
As far as I know ruby `Logger` uses mutexes to avoid log overlapping in threaded environment. 
So I don't see a problem as long as we log a single string.

**Comment by michaelklishin** [comment]
I don't see any limiting or comma-separated values on the linked line, either things have changed or this issue needs a bit of revisiting.
