### ISSUE TITLE
Is this project alive? 

### ISSUE THREAD

**Issue by nazarhussain** [jondot/sneakers#242]
Hello Dear, 

I was in need to implement a message broadcasting queue in my system so why thinking to use `sneakers`. But have few concerns here: 

1. 53 Open Issues
2. 22 Unmerged pull requests 
3. Last release 10 months ago 
4. Last comment on issues by author 48 days ago 
5. 1 comment on open issues in last month 

Is this project still alive?

**Comment by jondot** [comment]
It is alive. Most of the issues and pull request are still under discussion.

**Comment by nazarhussain** [comment]
Quick response makes it clear that project is still alive. Keep it up!

**Comment by gabrieljoelc** [comment]
Quite a few of those discussions are pretty stale though. 😁 Anyway we can
inject some life into some of the PRs?

**Comment by jondot** [comment]
Definitely, if there's something that you think must be merged in please let me know by @mention.

I've been tracking the issues mostly passively, part of my morning routine for all of my open source projects. Since there are plenty of mission-critical sneakers deployments right now and people are pretty happy with the existing feature set, it would be wrong for me to decide what's really critically missing by myself, and risk disrupting their production deployments. So by all means - pitch in and let me know :)

**Comment by nazarhussain** [comment]
@jondot Being author you know most of the sneakers and can better plan/decide on the project roadmap. If there are many mission-critical deployments it does not mean to halt the project.  For me or any other open source enthusiastic a project without no release in 10 months (around a year) is disrupting. Please prepare a roadmap for this project so all contributors can pull up their time to contribute as per that roadmap. What do you think?

**Comment by jondot** [comment]
I think, being a good open source project does not depend on "last release", and regardless to that in no way it is halted. This is an open source project. And specifically this one has an open door policy for pull requests, so if you find something missing please submit one, this can be code or docs.

**Comment by michaelklishin** [comment]
@nazarhussain sorry to be so harsh but if there's something "disrupting" about an open source project for you, you either help or keep it to yourself. Maintainers are human beings who have families and lives. Well, at least some of us are trying to.

**Comment by michaelklishin** [comment]
@jondot it's true that Sneakers is a project that is fairly easy to contribute to but there is one thing that I've been observing in the last year or so: pull requests take *months* to merge, even if they are trivial. This is definitely something that the users and contributors cannot do much about. On the RabbitMQ team we give external pull requests some of the highest priority to not discourage contributors. It's better to reject a PR in a few days than not respond for 8 months.

I volunteer to become a contributor to Sneakers to handle minor changes, issues that are questions (we really need a mailing list for those), Bunny bumps when I produce new releases, and so on. I definitely don't plan to pull the trigger on any significant decisions.

**Comment by michaelklishin** [comment]
There is a roadmap Markdown document that's effectively blank and has been for a few years. I suggest it is removed and contributors are encouraged to work on existing GH issues first (even if the resolution is "won't fix" or "this is not an issue with Sneakers") for a while.

**Comment by jondot** [comment]
@michaelklishin that's an important feedback for me.
I think, sometimes, in open source external triggers are very important (such as this issue thread). As I want to give the best of my time to all of my projects, it is always important to listen.

I'll gladly add you as a core contributor, since I've been a fan of your work for a while it will make me happy :)

For me, I always keep a minimalist approach to features, once a product is arriving to a stage that it is simply doing what it says on the tin. There will always be temptations to "add another feature", and "support framework X", however I always hope outside concerns would be built as an outside-thing, which is how I experienced healthy ecosystems grow. 

With that in mind, perhaps it's time to also welcome other core contributors, it may be a good time as any.

Personally, I'll put away other projects I planned for this weekend in favor of this move. I think it is important 👍

**Comment by jondot** [comment]
@michaelklishin @rud @gabrieljoelc @norman guys, you now have push access, you're welcome to accept the invite and be part of the core committer group. Welcome! 🎊 

As I mentioned above, I'll set the time to do cleanups, close some loose ends and bring this newly found collaborative effort about.

**Comment by michaelklishin** [comment]
@jondot thank you, I still don't have the permissions to merge pull requests, though.

**Comment by michaelklishin** [comment]
Provided that we have decent test coverage it shouldn't take long to review and merge or close most PRs. I'll do my best to help.

**Comment by michaelklishin** [comment]
@jondot sorry, I'm an idiot, I haven't actually followed a link to accept your GH invitation.

**Comment by michaelklishin** [comment]
Down to 12 unmerged pull requests (could be < 10 if they all merged cleanly) in an hour. I guess that counts for "alive".

**Comment by gabrieljoelc** [comment]
@nazarhussain thx for triggering this, thx @michaelklishin caring about this project, thx @jondot for your consideration and for building this in the first place!

> There will always be temptations to "add another feature", and "support framework X", however I always hope outside concerns would be built as an outside-thing, which is how I experienced healthy ecosystems grow.

I very much appreciate the keep-sneakers-flexible philosophy that this project has had, and I do think that `sneakers-rails`, `sneakers-redis`, etc. should happen outside of this repo. However, I think that we need more discussion within this repo on moving forward with those "outside "concerns".

**Comment by mjonas87** [comment]
Woot! Thanks all! Let me know if I can be of any help.

**Comment by jondot** [comment]
Great job guys! This is inspiring! :thumbsup:

**Comment by rud** [comment]
@jondot thank you for the invitation to directly participate, however I'm no longer actively involved with the project where we used sneakers. I'm happy to see the renewed interest in the project, it is a great building block for flexible solutions.
