### ISSUE TITLE
Is it possible to rate limit a worker?

### ISSUE THREAD

**Issue by barbolo** [jondot/sneakers#297]
For example, to perform a maximum of x jobs/minute or x jobs concurrently.

**Comment by michaelklishin** [comment]
In a way it is, by limiting [channel QoS](http://www.rabbitmq.com/confirms.html) (see [doc guide 1](https://github.com/jondot/sneakers/wiki/Configuration), [doc guide 2](https://github.com/jondot/sneakers/wiki/Handling-different-workloads))

**Comment by barbolo** [comment]
Thanks. I'm still trying to understand it.

If I have 20 servers, and each server is running a single sneaker process with 50 threads (i.e. 50 workers), if I set prefetch = 10, what will happen?

1. Max of 10 jobs will be processed simultaneously;

2. Max of 200 jobs will be processed simultaneously;

3. Max of 10.000 jobs will be processed simultaneously.

1 looks like a global limit, 2 like a per server limit and 3 like a per thread limit.

Thank you.

**Comment by michaelklishin** [comment]
Since QoS is a per-channel setting, it entirely depends on whether you do connection sharing. If you do, then the prefetch value affects, well, everything that uses that connection. If not, each worker will open its own connection and channel, each having a separate prefetch value.

This limits how many [deliveries Sneakers will receive](http://www.rabbitmq.com/confirms.html). How many are "processed simultaneously" is a lot more involved, in particular when tasks are processed very quickly.

**Comment by barbolo** [comment]
Can I share a connection between servers so I can set a global limit? I'm sorry for the newbie questions.

**Comment by michaelklishin** [comment]
@barbolo yes, my comment above tried to explain what the options are. [This doc section](https://github.com/jondot/sneakers/wiki/Configuration#rabbitmq-connections) explains how it's currently done (master has one more option introduced recently in ).

**Comment by barbolo** [comment]
Thanks @michaelklishin. I'll take a look on all links.
