### ISSUE TITLE
Sneakers should URL encode the amqp:// url

### ISSUE THREAD

**Issue by pre** [jondot/sneakers#314]
I'm connecting using 
`Sneakers.configure amqp: ENV.fetch('RABBITMQ_URL'), ..`

RABBITMQ_URL is `amqp://user:password@hostname:port`

I happened to have `]` in the password, which made Sneakers explode. Connection worked after I manually URL encoded the RABBITMQ_URL (ie. `]` became `%5D`).

Suggestion: Sneakers should URL encode the AMQP url by default.

**Comment by Tensho** [comment]
I ran into the same problem, but I'm not sure it's `sneakers` responsibility, neither `bunny`, `amq-protocol`. I use `URI.escape(ENV[''RABBTIMQ_URL"])`, but that kills the beauty of implicit `RABBTIMQ_URL` catch up in `Bunny.new`.
@michaelklishin, what do you think about it?

**Comment by michaelklishin** [comment]
I don't know much about the environment used. Encoding is not a no-brainer because double-encoding is a thing. Also, encoding the entire URI is wrong: only part-by-part encoding is relatively safe.

RabbitMQ docs certainly mention URL-encoding of certain path segments. This is not a commonly requested things => `wontfix` until more interest rolls in.

**Comment by pre** [comment]
:okay.png:
