### ISSUE TITLE
Suggestion regarding Publishing

### ISSUE THREAD

**Issue by DannyBen** [jondot/sneakers#340]
Hi,

I have seen all the publishing related issues and [wiki page][1], and I would like to suggest something.

First, my understanding of the status quo:

1. It is understood that Sneakers is mostly about handling a request, and publishing is a "side topic".
2. It is clear to me that there is some demand for simple publishing support (myself included).
3. It is agreed that different people may want to develop their own publisher using their own requirements.
4. It seems that some users are already using the `Publisher` class.
5. It is agreed, and acceptable to not deal with the message itself, but rather leave it as a string for the user to handle as they see fit.

I would like to suggest this:

1. Polish the `Publisher` class a little. Personally, the only thing missing for me is a public `#close_connection` method (that should call `@bunny.close`)
2. Mention this class in the Wiki documentation as *one way* to do publishing, in case someone wants a no hassle way of simply sending one-off messages.

At least this way people know it is somewhat of a "supported feature". Right now, when I am using it I feel like I am using an internal Sneakers class rather than a documented feature.

[1]: https://github.com/jondot/sneakers/wiki/Publishing-messages

**Comment by michaelklishin** [comment]
Please submit PRs, they are specific and can be discussed.

One issue with making`Sneakers::Publisher` a part of the public API is that should it ever change (e.g. by accepting a connection instead of automagically opening one), it would break a lot of code. I'd rather make `Sneakers::Worker#publisher` protected or even public, then publishers are a lot less likely to be instantiated directly.

I'm not sure what constitutes a "no hassle way of simply sending one-off messages". To me Bunny is an extremely convenient way and Sneaker's publishing API is entirely unnecessary. But it's too late to remove.
