### ISSUE TITLE
Closing connection on interrupt

### ISSUE THREAD

**Issue by DannyBen** [jondot/sneakers#341]
I noticed that no matter how I run my handler - either by running `sneakers work Processor --require boot.rb` or by creating my own `bin` which uses something like `Sneakers::Runner.new(handlers)`, whenever I press Ctrl-C to stop it, the server reports `client unexpectedly closed TCP connection`.

1. In the case of the `sneakers` binary, shouldn't `Interrupt` be rescued so that it exits gracefully?
2. When using `Sneakers::Runner` - is there a way for me to close the connection gracefully on `Interrupt`? I have tried rescuing and calling `runner.stop` but was unable to even reach the rescue block for some reason.

**Comment by michaelklishin** [comment]
The log warning [is entirely cosmetic](http://www.rabbitmq.com/networking.html#logging) in this case. Interrupt and signal handling is a lot more involved than having a `rescue` block. Specific PRs and ideas that would make it easy (or automatic) to close Bunny connections gracefully would be welcome, otherwise it's just a warning.
