### ISSUE TITLE
Sneakers over Hutch?

### ISSUE THREAD

**Issue by cassiopagnoncelli** [jondot/sneakers#368]
I understand Sneakers is blazing fast. I would like to have an unbiased opinion on Sneakers and Hutch for mission critical systems.

**Comment by nickstanish** [comment]
Likely going to be hard to get an unbiased opinion on Sneakers vs Hutch on a sneakers issue tracker, but my thoughts as someone who never heard of hutch and just looked it up, but has been in the process of implementing sneakers processing:

- Sneakers has ActiveJob integration (a really nice thing if you're using rails and are already on ActiveJob), it appears hutch does not
- Neither has a rails gem to make integrating with rails very easy
- Hutch appears to have more frequent maintenance recently
- Sneakers seems to have more documentation, though the quality could be better (a lot of docs are outdated or don't go into enough detail.. best bet is to check out the examples and/or read the source)
- Both use RabbitMQ and Bunny ruby lib, and worker threads so likely perform similarly with tweaking
- I don't see anything on hutch's readme about retries, but sneakers has a handler that will requeue failed jobs x times by using a dead letter exchange (you just need to setup your worker correctly to enable it)

**Comment by Tensho** [comment]
`sneakers` has a heavy dependency called `serverengine` (I guess primary for Windows support), which allows to manage processes/threads with whistles for any long-running application, but it requires you to understand low-level OS concepts, like session id, pipes, uids/gids, double-fork, signals, etc. I started to learn all this to be able to understand what's going on wrong with `sneakers` in my current project – accidental fails, sometimes poor log messages and sometimes too excessive, lack of deployment support (checkout the author reply to [Pidfiles per Sneakers Process](https://github.com/jondot/sneakers/issues/334).
). The `sneakers` author doesn't maintain the project, @michaelklishin keeps in on the health line, because he hasn't enough time for this project. Test coverage is pretty bad and obsolete in my opinion. There was a cruel `Timeout` epic recently discussed and fixed here, but it still hasn't released yet.

I appreciate all contributor efforts to this project, but it requires a lot of contributions 🙇  I'm researching `sidekiq` time to time with a thought to implement something similar for RMQ and from my shallow overview of  `hutch` it's more close to the process management subsystem to `sidekiq`, so maybe I it's worth to check out it first.

**Comment by olivierlacan** [comment]
@Tensho Thanks for the write up. [Hutch release frequency][2] isn't very encouraging.

Perphaps it's stable enough not to require frequent bug fixes but that seems unlikely somehow. My biggest issue with Sneakers right now is that it's blocking us from updating to the latest Bunny version which appears to have a fix to an issue we've been encountering. 

It doesn't seem to make sense that Sneakers locks down the Bunny dependency so much: `~ 2.11.0`. It feels like at the very least it should only lock on the minor: `~ 2.11`. Unless of course Bunny is very loosey goosey with semantic versioning and breaking changes between patch releases, which doesn't seem to be the case at least recently. The [changelog][1] is pretty great.

[1]: https://github.com/ruby-amqp/bunny/blob/master/ChangeLog.md
[2]: https://rubygems.org/gems/hutch/versions

**Comment by michaelklishin** [comment]
Hutch hasn't seen any significant changes in a while and it is significantly smaller in scope than Sneakers (that also doesn't get much love these days).
