### ISSUE TITLE
Rake dependency

### ISSUE THREAD

**Issue by vladimirtemnikov** [jondot/sneakers#422]
At this moment the latest version of `rake` is `13.0.1` but current dependency is still linked with `12.x`.
Could it be increased to i.e. `< 14` for runtime dependency?

**Comment by bumi** [comment]
The commit closing this issue misses the development dependency: https://github.com/jondot/sneakers/commit/415f283f7e634601528105323d0dac9663c5786d

`gem.add_development_dependency 'rake', '~> 12.3'`
why is it a development and runtime dependency?

**Comment by javierjulio** [comment]
@michaelklishin we recently installed sneakers but 2.11.0 where this wasn't a requirement, now with 2.12.0 our rake dependency was downgraded. There hasn't been a release in many years. Further there seems to be some commits for Ruby 3+ support since then. Any chance all that could get released?

**Comment by michaelklishin** [comment]
@javierjulio as I have explained in another issue, I do not have the permissions to produce releases, neither on GitHub nor on RubyGems.

**Comment by javierjulio** [comment]
@michaelklishin ah sorry about that. I hadn't seen it. Thank you for letting me know!

**Comment by michaelklishin** [comment]
I will try to find a way to reach @jondot in hope that I'd be given the permissions to produce releases. I'm a RabbitMQ core team member and quite used to helping maintain RabbitMQ-related projects.

**Comment by javierjulio** [comment]
@michaelklishin thanks! Yes, I know you are which is I reached. Also due to your merges in this repo. We've been using RabbitMQ (Bunny) for the past year and are testing sneakers just recently for a possible use case. Thank you for your help and contributions! I was concerned about using sneakers due to the many years without releases, also primarily because we upgraded to Ruby 3.0 recently and saw that those changes don't appear to be in a public release.
