### ISSUE TITLE
Is still actively maintained?

### ISSUE THREAD

**Issue by pedrofurtado** [jondot/sneakers#458]
Related to: https://github.com/jondot/sneakers/issues/452

**Comment by biofects** [comment]
[bump]

**Comment by abuisman** [comment]
That is a real shame as I was just looking at it for a new project and then noticed the commit history.

**Comment by michaelklishin** [comment]
It depends on what you mean by "dead". Sneakers hasn't massively changed in years. I may have been less responsive as I have dozens of RabbitMQ projects to work on but at some point small  projects reach maturity and do not change much.

**Comment by michaelklishin** [comment]
Also, this is open source software, so instead of asking others to "actively maintain" something for you, you can contribute and ask for committer permissions. If anyone wants them
and is ready to review PRs, triage issues and answer questions, let me know.

**Comment by abuisman** [comment]
Hey @michaelklishin sorry if my message came across as entitled. I didn’t mean to say I deserve your free time. I just meant it would have been nice if the community had picked up rabbitmq some more over some other back-ends. 

Good point on contributing though. Do you have any thoughts on which areas there can be some nice improvements for new contributors?

**Comment by michaelklishin** [comment]
Right now I want to clear the PR backlog and reduce the number of open issues (including by closing them as too old or after triaging).

Like I said above, I think Sneakers has matured to the point I don't expect it to
accumulate many large features. It has a ton of work around integration tests, metrics,
concurrency and maybe efficiency, so basically operational areas that are never "solved" problems. But it has a fairly fixed scope otherwise IMO.

Sadly I don't have the permissions to add contributors. @jondot I would like to be able to :)
But I can merge PRs, update release notes and push tags, which can acts as a short term way of
producing new releases.
