### ISSUE TITLE
Testing Your Worker page is gone?

### ISSUE THREAD

**Issue by dbyron0** [jondot/sneakers#97]
The link to https://github.com/jondot/sneakers/wiki/Testing-Your-Worker at the end of https://github.com/jondot/sneakers/wiki/How-to:-running-a-stand-alone-worker takes me to a "Create new page" page.  Sure would love to see that testing info if it's still around somewhere.

**Comment by abezzub** [comment]
I need to setup sneakers to work with cucumber. Is there some documentation available?

**Comment by jondot** [comment]
@abezzub did you bump into wall using cucumber? I have workers tested under rspec and minitest, so i'm assuming it should work for cukes as well?

**Comment by abezzub** [comment]
how do I run sneakers during cucumber tests? Do I just run them as standalone app and let cucumber interact with it? or is there a way to make cucumber start sneakers workers?

**Comment by jondot** [comment]
Well basically a sneakers worker is just a plain Ruby class. You'd test it as any other object, with these semantics in mind:

1. a message gets in (you can craft a message at test time)
2. a worker does some side effects based on your own logic (IO, etc.)
3. a worker acknowledges/rejects/etc (worker return value)

So for (1) and (3) you just do the arrange and assert yourself like any other test. For (2) you can test as-is, mocking around the various worker dependencies.

Last step is integration. For this, there's no built-in sneakers framework since you want to interact with a real RabbitMQ broker. Which means running the worker as a process, feeding it some messages from a real RabbitMQ broker and letting it interact with it. You should take note that once configured properly, this kind of code path is already tested as part of sneakers (making sure workers can connect, can fetch messages, can acknowledge, etc).

However if you really want a full cycle this - like other such 'dirty' testing, is not a very clean job to do - you would need to delete queues, empty them, prepare a sanitary RabbitMQ broker for the tests etc., however there are gems that automate RabbitMQ via management API - so you can delete queues, empty queues, etc before such tests.
Having said that, since sneakers includes the runner - you can programmatically run the full-integation worker.

So, if you're referring to integration tests - so far it is "bring your own" but I would be happy at least to know how you would expect it to work.

**Comment by abezzub** [comment]
Yes, I want to have integration tests that verify producer and consumer work together correctly. Setup is not that hard - I use Circle CI and they provide clean RabbitMQ instance for every build. So if I understand correctly I just need to run a standalone process with workers before I start cucumber tests, right?

I do have unit tests to test workers in isolation, but I think it is important to have integration tests as well.

**Comment by abezzub** [comment]
I ended up implementing this class to bake sneakers worker into cucumber tests (tests use real RabbitMQ):
```
require "timeout"

class CucumberExternalWorker
  attr_accessor :worker_pid, :start_command

  def initialize(start_command)
    raise ArgumentError, "start_command was expected" if start_command.nil?

    self.start_command = start_command
  end

  def start
    puts "Trying to start #{start_command}..."
    self.worker_pid = fork do
      start_child
    end

    at_exit do
      stop_child
    end
  end

  private

  def start_child
    exec({ "RAILS_ENV" => Rails.env }, start_command)
  end

  def stop_child
    puts "Trying to stop #{start_command}, pid: #{worker_pid}"

    # send TERM and wait for exit
    Process.kill("TERM", worker_pid)

    begin
      Timeout.timeout(10) do
        Process.waitpid(worker_pid)
        puts "Process #{start_command} stopped successfully"
      end
    rescue Timeout::Error
      # Kill process if could not exit in 10 seconds
      puts "Sending KILL signal to #{start_command}, pid: #{worker_pid}"
      Process.kill("KILL", worker_pid)
    end
  end
end
```

And it can be called as following:
```
$sneakers_worker = CucumberExternalWorker.new("rake sneakers:run")
$sneakers_worker.start
```

**Comment by abezzub** [comment]
I guess above matches (2) from https://github.com/jondot/sneakers/issues/102

**Comment by jondot** [comment]
Closing and categorizing under 'to document', thanks all!
